# Connecting SQL Database

In [3]:
import pymysql

HOST = "localhost"
PORT = 3306
USER = "u6606405"
PASSWORD = "6606405"
DATABASE = "u6606405_mydb"

connection = pymysql.connect(
    host = HOST,
    port = PORT,
    user = USER,
    password = PASSWORD,
    )

In [8]:
cursor = connection.cursor()

cursor.execute("SHOW DATABASES;")

results = cursor.fetchall()

for row in results:
    print(row)

('information_schema',)
('test',)
('u6606405',)
('u6606405_mydb',)

In [9]:
cursor = connection.cursor()

cursor.execute(f"CREATE DATABASE IF NOT EXISTS {DATABASE}")
cursor.execute("SHOW DATABASES;")

results = cursor.fetchall()

for row in results:
    print(row[0])

information_schema
test
u6606405
u6606405_mydb

In [10]:
connection = pymysql.connect(
    host = HOST,
    port = PORT,
    user = USER,
    password = PASSWORD,
    database = DATABASE,
    )
cursor = connection.cursor()

cursor.execute(f"CREATE DATABASE IF NOT EXISTS {DATABASE}")
cursor.execute("SHOW DATABASES;")

results = cursor.fetchall()

for row in results:
    print(row[0])

information_schema
test
u6606405
u6606405_mydb

In [17]:
cursor = connection.cursor()

# God Bless "IF NOT EXISTS" Keyword
cursor.execute(
    """
    CREATE TABLE IF NOT EXISTS user (
        id INTEGER NOT NULL AUTO_INCREMENT,
        email VARCHAR(255) NOT NULL,
        fullname VARCHAR(255) NULL,
        PRIMARY KEY (id)
        );
    """
)
cursor.execute("SHOW TABLES;")

results = cursor.fetchall()

for row in results:
    print(row)

('user',)

In [18]:
cursor = connection.cursor()
# God Bless "IF NOT EXISTS" Keyword
cursor.execute("ALTER TABLE user ADD IF NOT EXISTS city VARCHAR(255) NOT NULL AFTER fullname;")
cursor.execute("DESCRIBE user")

results = cursor.fetchall()

for row in results:
    print(row)

('id', 'int(11)', 'NO', 'PRI', None, 'auto_increment')
('email', 'varchar(255)', 'NO', '', None, '')
('fullname', 'varchar(255)', 'YES', '', None, '')
('city', 'varchar(255)', 'NO', '', None, '')

In [26]:
cursor = connection.cursor()
cursor.execute("INSERT INTO user (email, fullname, city) VALUES (%s, %s, %s)",
               ("nemoz@mail.com", "Nemo", "Pathum Thani"))

connection.commit()
cursor.rowcount

1

In [28]:
users = [
        ( "ana@me.com", "Ana", "Phuket" ),
        ( "beer@me.com", "Beer", "Nonthaburi" ),
        ( "min@me.com", "Min", "Bangkok" ),
    ]

cursor = connection.cursor()

cursor.executemany("INSERT INTO user (email, fullname, city) VALUES (%s, %s, %s)", users)

connection.commit()
cursor.rowcount

3

In [31]:
import pandas as pd

df = pd.read_csv("./assets/user.csv")
users = [ tuple(row) for row in df.itertuples(index=False) ]

cursor.executemany("INSERT INTO user (email, fullname, city) VALUES (%s, %s, %s)", users)

connection.commit()
cursor.rowcount

10

## Assignment

In [35]:
DATABASE2 = "u6606405_mydb2"

connection2 = pymysql.connect(
    host = HOST,
    port = PORT,
    user = USER,
    password = PASSWORD,
    )

cursor2 = connection.cursor()

cursor2.execute(f"CREATE DATABASE IF NOT EXISTS {DATABASE2}")
# God Bless "IF NOT EXISTS" Keyword
cursor2.execute(
    """
    CREATE TABLE IF NOT EXISTS patient (
        id INTEGER NOT NULL AUTO_INCREMENT,
        hospcode INTEGER (10) NOT NULL,
        pid VARCHAR(255) NOT NULL,
        chronic VARCHAR(255) NOT NULL,
        PRIMARY KEY (id)
        );
    """
    )
cursor2.execute("DESCRIBE patient")

results = cursor2.fetchall()

for row in results:
    print(row)

('id', 'int(11)', 'NO', 'PRI', None, 'auto_increment')
('hospcode', 'int(10)', 'NO', '', None, '')
('pid', 'varchar(255)', 'NO', '', None, '')
('chronic', 'varchar(255)', 'NO', '', None, '')

In [39]:
df = pd.read_csv("./assets/chronic_2016_90_all.csv", low_memory=False)
# Selecting the rows
df = df[ [ "HOSPCODE", "PID", "CHRONIC" ] ]

# Renew a cursor
cursor2 = connection2.cursor()
patients = [ tuple(row) for row in df.itertuples(index=False) ]
cursor.executemany("INSERT INTO patient (hospcode, pid, chronic) VALUES (%s, %s, %s)", patients)

connection2.commit()
cursor.rowcount

642476

# 08 Data Retrieving

In [6]:
pip install SQLAlchemy

Collecting SQLAlchemy
  Downloading sqlalchemy-2.0.44-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from SQLAlchemy)
  Downloading greenlet-3.2.4-cp313-cp313-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\nemoz\miniconda3\lib\site-packages (from SQLAlchemy) (4.12.2)
Downloading sqlalchemy-2.0.44-cp313-cp313-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ------------------------ --------------- 1.3/2.1 MB 14.2 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 16.3 MB/s eta 0:00:00
Downloading greenlet-3.2.4-cp313-cp313-win_amd64.whl (299 kB)
Installing collected packages: greenlet, SQLAlchemy

   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   -------------------- ------------------- 1/2 [SQLAlchemy]
   ---------------------------------------- 2/2 [SQLAlchemy]

Successfully installed SQLAlchemy-2.0.44 greenlet-3.2.4
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd

df_uri = "mysql+pymysql://u6606405:6606405@localhost/u6606405_mydb"
sql = "SELECT * FROM user;"
df = pd.read_sql(sql, df_uri)
df

    id           email fullname           city
0    1  nemoz@mail.com     Nemo   Pathum Thani
1    2      ana@me.com      Ana         Phuket
2    3     beer@me.com     Beer     Nonthaburi
3    4      min@me.com      Min        Bangkok
4    5    alice@me.com    Alice        Bangkok
5    6      bob@me.com      Bob     Chiang Mai
6    7  charlie@me.com  Charlie      Ayutthaya
7    8    david@me.com    David        Pattaya
8    9      eve@me.com      Eve          Krabi
9   10    frank@me.com    Frank    Surat Thani
10  11    grace@me.com    Grace       Chonburi
11  12   hannah@me.com   Hannah         Rayong
12  13      ian@me.com      Ian   Samut Prakan
13  14     jane@me.com     Jane  Nakhon Pathom

In [85]:

df_uri = "mysql+pymysql://u6606405:6606405@localhost/u6606405_mydb"
sql = """
    SELECT * FROM patient;
"""
df = pd.read_sql(sql, df_uri)
df

            id  hospcode    pid chronic
0            1      9435  10002     I10
1            2      9435  10007     I10
2            3      9435  10019     I10
3            4      9435  10031    E119
4            5      9435  10036    E119
...        ...       ...    ...     ...
642471  642472     99782    996     J46
642472  642473     99782   9964     I10
642473  642474     99782    997     I10
642474  642475     99782   9982     J46
642475  642476     99782   9989     J46

[642476 rows x 4 columns]

In [84]:
df = df.groupby('chronic').count()
df.head(10).plot().bar()

TypeError: DataFrame.sort_values() missing 1 required positional argument: 'by'